name: voiceline_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  freezed_annotation: ^2.2.0
  go_router: ^16.0.0
  audioplayers: ^6.5.0
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  skeletonizer: ^2.1.0+1
  audio_video_progress_bar: ^2.0.3 # Check if we really need this
  path_provider: ^2.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  record: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  freezed: ^2.2.0
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1


flutter:

  uses-material-design: true